# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Check docs

on:
  push:
    branches: docs-checker
  schedule:
    - cron: '0 0 1,15 * *' # runs every 1st and 15th day in the month

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup pytho
      uses: actions/setup-python@v2
      with:
          python-version: '3.7'
    - name: Download artifact
      uses: valcikeric/download-base-artifact@master
      with:
        artifact: cached-docs
        path: cached-docs
        allow-fail: true
      continue-on-error: true
    - name: Install dependencies
      run: |
        pip install requests
    - name: Run docs checker
      run: |
        python3 libscheck.py
    - name: Save cached docs
      uses: actions/upload-artifact@v2
      with:
          name: cached-docs
          path: cached-docs/
      if: always()
 
